### ISSUE TITLE
News ?

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#10]
Hi heqro,

have you got news about your project ? No changes since 2 weeks ?

Thanks.

**Comment by Goldaracena** [comment]
Hi Tuxman,

I haven't done anything in the past few weeks. Lack of motivation, primarily. I expect to be back to working on it sometime soon, but cannot really put my finger on a certain date.

**Comment by Goldaracena** [comment]
There, I found motivation for fixing a batch of long-standing bugs. Closing "issue", I guess.
