### ISSUE TITLE
Notes about the search bar 

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#11]
Hello heqro,

I have some remarks about searching applications via your search bar. No problem to view all applications referring to the first letter. On the other hand, if I target an application in particular (for example, LibreOffice), and I indicate the 2 or 3 first letters (lib), the application grid offers other applications while I should only get LibreOffice . Even finding if I am looking for another application via its name (example: VLC) in the search bar. Nothing is displayed. In short, if I do research on a single letter, it's ok. On the other hand, if I use more than one letter in the search or I am looking for the application via part of its name, it's not perfect. 

Regards.

**Comment by Goldaracena** [comment]
Fixed in [commit 64df6f1](https://github.com/heqro/stupid-simple-launcher/commit/64df6f1a80ae79b8e0925384ed73e0b7eca42380).
