### ISSUE TITLE
Favorites bar when paginating

### ISSUE THREAD

**Issue by Goldaracena** [heqro/stupid-simple-launcher#12]
Progress is being made. The favorites will be able to have a size that's different to the applications grid as well.

![image](https://user-images.githubusercontent.com/58432067/162536728-b556b17f-0386-4012-918b-f7eff452c03a.png)

**Comment by Tuxman2** [comment]
Ok. I'm ready to test it. ;-)

**Comment by Goldaracena** [comment]
Hi, today is my birthday and I'd figure it would be great to give you a sneak peek of how things currently are looking in the menu. I am planning to improve the favorites bar, but this is how it looks right now. If you happen to remember how to upgrade the menu, you will find the following .tar.gz to have the newest updates. I think the basics should mostly work. I still want to try luck polishing some rough edges I've found here and there.

[stupidsimplelauncher_220414.tar.gz](https://github.com/heqro/stupid-simple-launcher/files/8492175/stupidsimplelauncher_220414.tar.gz)

**Comment by Tuxman2** [comment]
Hi heqro,

with a little delay, happy birthday to you. ;-)

I will test your new version. Do you plan that the favorites bar allow the user to reorder the favorites applications (through mouse, touchpad, touchscreen for example) ? Do you plan to define a design for the favorites bar ?

Thanks.

Regards.

**Comment by Goldaracena** [comment]
> Do you plan that the favorites bar allow the user to reorder the favorites applications

Favorites are automatically ordered by their date of insertion.

> Do you plan to define a design for the favorites bar ?

Yes, I am still deciding on a few of them.

**Comment by Tuxman2** [comment]
Hi heqro,

I see that 'Launchpad plasma' applet allows the user to reorder the favorites applications in their favorites bar (you hold down the left click and you can reorder the favorite applications). Also, 'Launchpad plasma' applet allows the pagination when you click on these buttons:

![buttons](https://user-images.githubusercontent.com/23556606/163711035-839763b8-886b-4058-b5b5-58753879744f.jpg)

So, when you click on the second button, it paginates on the second page, when you click on the first, it paginates to the first page. I think this feature is good for people who don't have a touchscreen. They can easily switch from one page to another by pressing the buttons. We find that kind of thing on Gnome 40/41 too.

Perhaps you can check the source code of 'Launchpad plasma' applet to see how they manage the two things above.

Thanks.

Regards.

**Comment by Tuxman2** [comment]
Hi heqro,

news ?

Regards.

**Comment by Goldaracena** [comment]
Hi,

I've just pushed whatever changes I had done up until now. There's a [commit](https://github.com/heqro/stupid-simple-launcher/commit/f156fbba65e134f3ced633e0965f6737d5f5bed6) that adds the requested functionality of clicking in a dot to swap the current page, I find it hard to press though, but on Launchpad I do as well. It makes sense to have it though.

I still am looking to implement the drag and drop but I have yet to start any effort towards that. Finals are coming within a month again so I will see how I manage. 

Cheers.

**Comment by Tuxman2** [comment]
Great :+1: 

I will download the source code of the master branch and I will test it. 

Thanks.

**Comment by Tuxman2** [comment]
I tested the last version from your Master branch but I've got a problem. I can't launch the menu. The system gives me these two message errors:

file://home/...../Stupidsimplelauncher/contents/ui/main.qml:59:9: Type MenuRepresentation unavailable
file://home/..../Stupidsimplelauncher/contents/ui/MenuRepresentation.qml:422:44: PlasmaExtras.Highlight is not a type.

I download again the version from the Master branch with the git command. I will test again to see if it works. But can you check it ?

Thanks.

**Comment by Goldaracena** [comment]
Okay. It should work now.

This is the second time that something like this happens; I get warnings from the KDE environment that something is deprecated and should be using something else. I swap to that "something else", boom, everything breaks for the rest of people! 

At this point I should not pay attention to any warning messages :/

**Comment by Tuxman2** [comment]
Ok, I download the new source code from your Master branch and I will test it. ;-)

Thanks.

!!! News !!!: Here are my impressions on the latest version:

Pros:

- The menu is excellent with the new features (pagination, search bar choices, sessions buttons, favorites, ....).
- Works very well with Wayland (pagination, ....).
- The menu is better after each versions.

Cons:

- Put a frame (blue) around the applications grid. I preferred before, that is to say, display the applications grid as it is. Possibility to return to the 'old display' ?

Thanks.

**Comment by Blad3forc3** [comment]
Just tried this off github and the scrolling has got really slow with the mouse wheel

**Comment by Goldaracena** [comment]
Okay, just pushed a fix. It should work now as it did back then.

**Comment by Goldaracena** [comment]
> Put a frame (blue) around the applications grid. I preferred before, that is to say, display the applications grid as it is. Possibility to return to the 'old display' ?

I will try to make it soon. I felt it made sense because at this point it was the only element without explicitly drawn boundaries.

> The menu is excellent with the new features (**pagination**, search bar choices, sessions buttons, favorites, ....).

Yes! I tried it with a friend's computer that has tactile display and I was delighted to know how good the experience was!

**Comment by Tuxman2** [comment]
@heqro: Or you can make an option to enable/disable that frame around the applications grid. If you enable the categories sidebar, the menu looks good with it (see your first screenshot in the README file), but when you don't enable the categories sidebar, it is very strange to see a frame around the applications grid, because in this case, the menu looks more like a tablet style menu. You know what I mean.

**Comment by Goldaracena** [comment]
Yes, I will get around to it in the coming days now that the dragging and dropping in the favorites list is added.

**Comment by Tuxman2** [comment]
Your menu is close to perfection. :-D
It will be the best. ;-)

**Comment by Goldaracena** [comment]
I feel it's worth the job because it's useful to you guys :)

For me, the menu will be ready once it can create folders just like the Gnome menu does. But I still have a long way to go in plasmoid development to do that.

**Comment by Tuxman2** [comment]
I am very impressed with the work you have done so far. You are very responsive and you listen to the advice of users, which I really appreciate. I don't like menus resembling those of Windows (like those that can be seen on Windows 10 or 11, they do not seem to me ergonomic). I much prefer menus like your or that of Adhe (Launchpad Plasma) because they offer another way to use a menu (simpler, more ergonomic).

**Comment by Goldaracena** [comment]
Thank you for your kind words. The nice comments from the community really helps me keep pushing forward with this project. I wouldn't have gotten this far if I hadn't ever shared this work in the first place.

**Comment by Tuxman2** [comment]
This is why I appreciate the world of Free software compared to closed software, each bringing their ideas, their know-how, we can develop good projects. ;-)

The proof here. :-)

**Comment by Tuxman2** [comment]
Is the blue frame can be enabled/disabled for the applications grid in the new 1.9.0 version ?
Or we have to wait in the next release ? 

Thanks.

**Comment by Goldaracena** [comment]
It is not an option as of now.

**Comment by Tuxman2** [comment]
> It is not an option as of now.

OK. Is there a way that this feature can be added soon ? 

This (blue) frame doesn't bother me when the categories are displayed, on the other hand, when I only display the applications grid (with the favorites bar or with the session buttons), I don't find it aesthetic. Especially for use of "tablet" type.

So, can you have a look on it if it doesn't bother you ?

Thanks a lot.

Regards.

**Comment by Goldaracena** [comment]
Here it is.

[versionWithoutRectangle.tar.gz](https://github.com/heqro/stupid-simple-launcher/files/8633178/versionWithoutRectangle.tar.gz)

**Comment by Tuxman2** [comment]
Thanks. I will test it. ;-)

As I said, perhaps you can add this kind of feature in the next version. An option to enable/disable (blue) frame for the applications grid.

Regards.

**Comment by Tuxman2** [comment]
> Here it is.
> 
> [versionWithoutRectangle.tar.gz](https://github.com/heqro/stupid-simple-launcher/files/8633178/versionWithoutRectangle.tar.gz)

Perfect. :-)

Well, as I said in my previous message., an option could be added in the preferences of the menu to enable/disable this (blue) frame for the applications grid. It could be a new feature.

What do you think about it ?

Regards.

**Comment by Goldaracena** [comment]
Hello.

I'm busy right now but perhaps I will get around to it some day.

**Comment by Tuxman2** [comment]
No problem, just take your time. ;-)
