### ISSUE TITLE
Expand the Category Position Vertically

### ISSUE THREAD

**Issue by Blad3forc3** [heqro/stupid-simple-launcher#14]
![Carátula](https://user-images.githubusercontent.com/39629883/167288758-86454f59-2056-438f-8c14-9648437ab86b.png)
I have highlighted the normal category area in blue. Could it be extended so it take up the red area vertically?

**Comment by Goldaracena** [comment]
It might be done, but it shouldn't be done. The menu is designed as it is now to withstand a tremendous amount of different use-cases people have been proposing over time. Such use-cases include, for instance, having the categories sidebar extend for as much as the user wants to while keeping it the rest of the menu as clean as possible. This means the edge cases have to work properly as well:

![image](https://user-images.githubusercontent.com/58432067/168415571-7316a027-3746-4715-be30-bd2d2dba6208.png)

Now, imagine if the categories block was to be extended for the entirety of the screen's height. Then, not only would the search bar but also the session control bar would be shifted to the left, just like the applications block was. Conversely, if the categories block was to be as narrow as possible, the same shift would happen in the opposite direction to the entirety of the block.

I doubt there is an easy solution to this problem that doesn't involve hard coding things here and there. Moreover, I like it much more as it is right now.
