### ISSUE TITLE
Right Configure Stupid Simple Launcher from desktop freezes options screen

### ISSUE THREAD

**Issue by Blad3forc3** [heqro/stupid-simple-launcher#18]
Recently i cant configure any options from the configure screen.
I right click from the desktop select configure stupid simple launcher and the options pop up but everything has frozen.
I have to kill plasmashell but it doesnt resolve not being able to select options. Other widgets configure fine

**Comment by Goldaracena** [comment]
Hi, I have just installed the menu again in a fresh Fedora 36, Plasma 5.25.3 installation. I can't reproduce that problem :/

**Comment by Goldaracena** [comment]
Could you please tell me if this issue still is happening to you?

**Comment by Blad3forc3** [comment]
This issue is not happening anymore
