### ISSUE TITLE
Question: What is the ribbon that stays unchanged when changing categories?

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#23]
What is the ribbon with application icons that stays unchanged when changing categories, and how can it be edited?

![image](https://user-images.githubusercontent.com/3447868/212962308-0ed677f5-87c8-41ef-b97d-e351db96b127.png)

it doesn't change with categories, but it changes rather often, and I don't know on what criteria.

**Comment by Goldaracena** [comment]
It is an on-by-default favorites list. It changes, for instance, when you change your current Activity. It can be disabled in options.

Actually, if there's anything else new that's bugging you, chances are there is a switch to turn it off. I just try to add and enable new features to make it sure they are discovered.

**Comment by cipricus** [comment]
I was on the point of closing this myself. Thanks. I love it. I had indeed enabled favorites as default too.

![image](https://user-images.githubusercontent.com/3447868/212966270-ce931752-51ea-4155-8ea7-21049a600ebc.png)
