### ISSUE TITLE
The on-by-default favorites list should be scrollable with the mouse

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#26]
While the mouse/touchpad is needed to [change to and between categories](https://github.com/heqro/stupid-simple-launcher/issues/24), the opposite happens with the on-by-default favorites list/ribbon that we discussed in [another topic](https://github.com/heqro/stupid-simple-launcher/issues/23): there, if many favorites are enabled, some are hidden, and there is no scroll to access them with the mouse, only arrows can be used.

Also, to get from the grid to the favorites ribbon, only the arrows can be used: we can click something on that list and an app is started, but we cannot go from the grid to the favorites horizontal list (and eventually access the hidden ones) with the mouse without opening some app when clicking, we have to use the arrows.

![image](https://user-images.githubusercontent.com/3447868/213118373-83ea1042-8470-4a19-9b6d-bb2d83c372ff.png)

![image](https://user-images.githubusercontent.com/3447868/213118542-d50a5347-14ee-4ed3-8e86-ced36e4e1218.png)

**Comment by Goldaracena** [comment]
The master branch now has this functionality. Please test it when you have time and tell me what you think. I don't have access to a mouse, so in my case I have tested it against my touchpad's side swipe.

**Comment by cipricus** [comment]
Is this default? I have installed the 2023.01.18 version but I don't see it. The scroll/swipe that works on the grid does not work in the favorites list.

**Comment by Goldaracena** [comment]
It's in the master branch. The contents you see inside this repository's "v1" folder correspond to what I call the master branch.

This change is not present in the KDE Store version as of now. I am going to wait a few days for that.

**Comment by cipricus** [comment]
It works.

**Comment by cipricus** [comment]
It has some glitches, like a scrollbar in the middle of the screen (?) but I'll test later with the more stable version before posting other issues.

**Comment by Goldaracena** [comment]
Could you show me a screenshot?

**Comment by cipricus** [comment]
I will try. But first, please tell me if this is a proper way to install the master version: I install an older version, and then delete the contents of the folder ` ~/.local/share/plasma/plasmoids/stupidsimplelauncher` (or create that folder) and copy there the contents of `/stupid-simple-launcher-master/v1`, then logout and back.

**Comment by cipricus** [comment]
I will try. But first, please tell me if this is a proper way to install the master version: I install an older version, and then delete the contents of the folder ` ~/.local/share/plasma/plasmoids/stupidsimplelauncher` (or create that folder) and copy there the contents of `/stupid-simple-launcher-master/v1`, then logout and back.

After that, adding the widget, default settings:

![image](https://user-images.githubusercontent.com/3447868/213434593-d7523f5a-9759-479d-9993-ebd8edb47aa5.png)

After a few settings:

![image](https://user-images.githubusercontent.com/3447868/213434903-3fbcab74-3405-4dbd-a0ab-1fef31e9f181.png)

By the way, no matter that odd thing, I think that no scroll bars should be visible, at least optionally, at least not for the favorites bar, although scrolling should be possible. Especially the horizontal scrollbar for the favorites list looks odd imo, I'd largely prefer the old situation with no scrolling action to this scrollbar being visible all the time. By the way, I personally won't use the favs list because favorites grid should be my default view, I have posted this issue for logical reasons.

Without favorites list/bar:

![image](https://user-images.githubusercontent.com/3447868/213436110-5b89c33d-3c22-403e-9922-c7a5ab758cf2.png)
