### ISSUE TITLE
Menu should close when executing a right-click action on an item (like "open location", "edit application" or "new window")

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#28]
For example, for a searched file, when selecting "open location", the expected behavior is for the menu to close and the file manager window to be visible with that location. In the same way, if the right-click option for a browser "new window" or "new private window" is selected, the expected behavior is for the menu to close and the browser to be seen automatically. 

![image](https://user-images.githubusercontent.com/3447868/213131263-49b9c721-acfc-4158-9b03-ecfb884816f8.png)

The same is the case with other such options. 

At the present, the menu stays open while the intended applications are open behind it. The requested behavior is default in most menu widgets.

**Comment by Goldaracena** [comment]
This has been fixed in the master version. If you happen to be running the master version, this should work now. If it does on your end (provided you are running the master version), I can close this issue and upload all the new goodies from today and yesterday to the KDE Store.

**Comment by cipricus** [comment]
> If you happen to be running the master version

how do I get that?

**Comment by cipricus** [comment]
Great. I have copied the files from master into the widget folder and it works.
