### ISSUE TITLE
No option to change the general icon size

### ISSUE THREAD

**Issue by Blad3forc3** [heqro/stupid-simple-launcher#29]
The option to change the general icon size has disappeared

**Comment by Goldaracena** [comment]
It's under the new settings tab dedicated to tweak it in better detail with a live preview

**Comment by Blad3forc3** [comment]
ok yes sorry but the icon does seem to "jump" in size. Try scaling the icon very slowly from a very large size and it doesnt scale down or up constantly. At a a guess i would say size 148 it jumps up or down in size

**Comment by Goldaracena** [comment]
Yes but the same thing happens with the category customizer, the icons come in certain sizes like 64px, 32px and so forth. They don't scale as far as I know. Try changing the KDE panel size and the same thing will happen to their icons

**Comment by Blad3forc3** [comment]
ah so this more likely a bug in kde instelf?

**Comment by Goldaracena** [comment]
I think it's just down to the icon packagers packaging them only in certain sizes. Perhaps it does not happen when using SVG based images, but that is not how icon packages are distributed, as far as I know. I have had this issue happen every time I tried using icons when developing a plasmoid.
