### ISSUE TITLE
Feature request: add option to display search results as list

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#31]
While applications icons look fine and even better in a grid, searches, and especially results of file searches are better if listed in lines for some users (who, for example, work with many text files) .  

This feature is present in "Tiled Menu" widget, for example:

![image](https://user-images.githubusercontent.com/3447868/213441828-887e897e-1b46-4917-803b-94b3f40de408.png)

While in a grid the same search looks like this:

![image](https://user-images.githubusercontent.com/3447868/213440874-0b8687f7-957d-4549-a120-9fb70470ef36.png)

A list is much more informative and helps to identify a file when the files searched and the search results are very numerous, have similar or long names or the same name but with different locations.

(What I dislike in Tiled Menu is the fact that a list is always present on the screen - a list of apps when no search is made. That is why I prefer your widget. But I would prefer a list for searches in any menu.)

*****************
Maybe I'm letting myself go here with all these request as if looking for the perfect launcher (when in fact I'm really looking for that). Sorry, and please advise me to let go if the case be.

**Comment by Goldaracena** [comment]
The current system also allows for more entries to be shown at once, which it's something I always appreciate and miss from other options like KRunner or any menu out there for that matter. The file information shown by Tiled Menu is present on the tool-tips this menu shows for each entry matching your query.

It could be interesting to have it as an option for some Stupid Simple Launcher v2 when/if it ever lands.

**Comment by cipricus** [comment]
> more entries to be shown at once, which it's something I always appreciate and miss from other options like KRunner or any menu out there

The tooltips are great! Krunner tries to squeeze the path in the same line, usually not fitting, I see that because I've made it screen-wide with a window rule. 

Why more entries are shown in your launcher than in Krunner? Repeating my search I see 12 results in your menu, in Tiled menu and in the Plasma Drawer menu, but only 9 in krunner. Why is there a difference? Aren't all search based on Krunner? 

Tiled Menu shows searches in list with path (the problem is that a list is always visible).

**Comment by Goldaracena** [comment]
> Why more entries are shown in your launcher than in Krunner? 

I have no idea. Plasmoids behave in mysterious ways. I intend to (eventually) release a v2 of this menu to avoid the whole plasmoid shenanigans. This would allow me to have complete control of how to call the Plasma database for applications and search results. 

I have no idea how long that's going to take, if I ever manage to make it through the initial steps.

**Comment by cipricus** [comment]
All the best to you, and thanks again! I'll keep an eye on this menu, even when I'll try others.
