### ISSUE TITLE
Tooltips when hovering session buttons.

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#5]
Hi heqro,

The session buttons (logout, restart, shutdown, ...) are available on the screen, but we don't know which button does what. So, I think if we could have tooltips when we hovering session buttons, it will be a good thing. Do you think this is something that you can add as a feature in a new version before you get busy with your exams ?

Thanks.

Regards.

**Comment by Goldaracena** [comment]
hi, I just added a tooltip that triggers on hovering and is enabled by default. Should be uploaded to the place you can download it from by now.

**Comment by Tuxman2** [comment]
Thank you very much. :-)

Stupid-simple-launcher has the whole necessary items now. I'm very happy and I can say that it is the best. I saw you plan to add more features in the future, it is amazing. Excellent work. ;-)

**Comment by Goldaracena** [comment]
Thanks for your kind words. Closing the issue now😁
