### ISSUE TITLE
The color of the words in the search bar is in black.

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#7]
Hello again,

I talked about it in another post. When I write in the search bar, the words are black. I can not define the opacity to the maximum otherwise I can't see the words displayed when I use a dark theme.  I would like to see the words in white or light grey when I use a dark theme. How to solve it ?

How are the words in the search bar managed (color, size, ...)?

Thanks.

**Comment by Goldaracena** [comment]
Hello, could you please tell me what combination of color scheme + plasma style are you using? Please recall, as per my previous screenshots, that I am using at all times the user's color scheme yet the words were white/gray. 

Do you happen to know if you have the same issue across other KDE applications?

**Comment by Tuxman2** [comment]
Hello heqro,

I'm using this KDE theme: https://github.com/yeyushengfan258/DeepinV20-kde

For plasma: deepinv20-dark style. For color scheme: DeepinV20-light style.

**Comment by Goldaracena** [comment]
Yup, that was one of the weird ones. It seems the placeholder text color was to follow the color scheme but the text color itself followed the plasma style one (or something along those lines). Just fixed it and could prove the fix works under your color.

It was the "dark style" and "light style" combination that made it absolutely clear.
