### ISSUE TITLE
Suggestion for the applications grid

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#9]
Hello heqro,

I have a suggestion to make you. When the applications grid can not be displayed on a single page (for example, when the screen is small), it is displayed on multiple pages. What I have noticed on the Gnome desktop, and on the Launchpad Plasma and OSXlaunchpad menus is that those use "buttons" to go from one page to another. See attached pictures (rounded in red). So that kind of thing can facilitate the use of a mouse, touchpad or touchscreen if you want to display all the grid icons when the button is pressed that corresponds to the page desired (first, second or more). This kind of thing can be easier to implement than a scrolling of the grid for touchscreen. I hope my explanation is simple to understand. What do you think about it ? 

Thanks.

Regards.

![appgridbuttons](https://user-images.githubusercontent.com/23556606/154842898-cee8a305-1558-41dd-bada-fb87bf6ed0f2.png)

![debgnome402](https://user-images.githubusercontent.com/23556606/154842907-1460adac-8975-4fb4-b45a-75cfee4e25a5.jpg)

**Comment by Goldaracena** [comment]
Found something on the Internet that may help, I enclose a video compressed as zip. I've been substituting the entirety of the applications grid for rectangles for the sake of simplicity. This shows me swiping sideways and changing the current rectangle. This also works by dragging with my mouse/touchpad as well. It works well enough on Wayland... but for some reason on X11 it only works when I swipe left (when I swipe right it doesn't work😥)

[2022-02-21 21-57-19.zip](https://github.com/heqro/stupid-simple-launcher/files/8112075/2022-02-21.21-57-19.zip)

If you want to test on your system, I enclose a .zip file with the code:

[stupidsimplelauncher_substitutingRectangles.zip](https://github.com/heqro/stupid-simple-launcher/files/8112049/stupidsimplelauncher_substitutingRectangles.zip)

ETA on this? I can't really tell. Wayland still is tremendously sluggish on my machine. I prefer to stay away from it up until things really start to work in there.

**Comment by Tuxman2** [comment]
Thanks.

I will test it as soon as possible and I will tell you what I think about it. I'm using Wayland now because it is more adapted for touchscreen and convertible laptops. Wayland works well with the last stable version of KDE : KDE plasma 5.23.5 at my house. I will switch to KDE plasma 5.24 in a few weeks (probably when KDE plasma 5.24.3 will be available and stable).

Regards.

**Comment by Tuxman2** [comment]
Hi heqro,

Well, it is very good. It works well on Wayland. If you implement it to the applications grid, it will be great. It will looks like similar what we find on Launchpad plasma menu and Gnome desktop.

Of course, if the applications grid is displayed in one page, this kind of thing must not be used. Another thing is that it must not be interfered with the categories list and with the favorites list displayed above the applications grid. But I think you have an idea how you will be implemented it with the whole menu. Once again, the solution you found is very good. Perhaps adding dots like we have in the Gnome desktop (see picture above (rounded red)), could be a good thing too to implement.

Well, your menu is getting better and better  after each version. ;-)

Regards.

Note: Wayland seems to be a priority for the KDE plasma developers. In fact, xorg is very old and Wayland must be replaced it in the future.

**Comment by Goldaracena** [comment]
Closing because this [has been recently implemented](https://github.com/heqro/stupid-simple-launcher/commit/f156fbba65e134f3ced633e0965f6737d5f5bed6#diff-a639b31fff10606874a945e6ad460be586d944b43c81798673df141d966eaeacR111).
